name: contacts_app_io
description: contacts app server
version: 1.0.0
homepage: https://github.com/graphicbeacon/flutter-mongodb-contacts-app-2022

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  mongo_dart: ^0.7.4
  shelf: ^1.2.0
  shelf_hotreload: ^1.1.0
  shelf_router: ^1.1.2
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
